name: Function Test

on: push

jobs:
  build: 
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SetUp Node
      uses: actions/setup-node@v4
      with: 
        node-version: 18
        
    -  name: Check Node version 
       run : node -v
       
    -  name: Run  Application
       run : node index.js
       
    -  name: install dependcies
       run: npm install

    -  name: Fix Jest Permission
       run:  chmod +x ./node_modules/.bin/jest

    -  name: Run Test
       run: npm test

